"""empty message

Revision ID: 5fa2e5701880
Revises: 85c4a7496722
Create Date: 2018-11-16 11:00:48.107775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa2e5701880'
down_revision = '85c4a7496722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breed', sa.Column('inheight', sa.String(length=10), nullable=True))
    op.add_column('breed', sa.Column('outheight', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breed', 'outheight')
    op.drop_column('breed', 'inheight')
    # ### end Alembic commands ###
